// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache License Version 2.0",
            "url": "https://github.com/mrzack99s/coco-captive-portal"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/adm-signed": {
            "get": {
                "description": "Get admin signed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get admin signed",
                "operationId": "adm-signed",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/authentication": {
            "post": {
                "description": "Check credential to get access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authentication",
                "operationId": "authentication",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CheckCredentialType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AuthorizedResponseType"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/check-is-administrator": {
            "post": {
                "description": "Check is administrator",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Check is administrator",
                "operationId": "check-is-administrator",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CredentialType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/config": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get config",
                "operationId": "get-config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ExtendConfigType"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Set config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Set config",
                "operationId": "set-config",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ConfigType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/count-all-session": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Count all session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Count all session",
                "operationId": "count-all-session",
                "responses": {
                    "200": {
                        "description": "count",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/get-all-session": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get all session",
                "operationId": "get-all-session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.SessionType"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/get-captive-portal-config-fundamental": {
            "get": {
                "description": "Captive portal config fundamental",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utils"
                ],
                "summary": "Captive portal config fundamental",
                "operationId": "get-captive-portal-config-fundamental",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CaptivePortalConfigFundamentalType"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/initialize": {
            "get": {
                "description": "Get initialize secret to get access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get initialize secret to get access",
                "operationId": "initialize",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.InitializedType"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/is-exist-initialize-secret": {
            "post": {
                "description": "Exist initialize secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Exist initialize secret",
                "operationId": "is-exist-initialize-secret",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.InitializedType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/kick-ip-address": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "To kick via ip address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "To kick via ip address",
                "operationId": "kick-via-ip-address",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SessionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/kick-username": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "To kick via username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "To kick via username",
                "operationId": "kick-via-username",
                "parameters": [
                    {
                        "description": "Parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SessionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/net-intf-usage": {
            "get": {
                "description": "Network Interfaces Usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Network Interfaces Usage",
                "operationId": "net-interfaces-bytes-usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/revoke-administrator": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Revoke administrator",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Revoke administrator",
                "operationId": "revoke-administrator",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/sign-out": {
            "get": {
                "description": "Sign out",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign out",
                "operationId": "sign-out",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/signed": {
            "get": {
                "description": "Get signed by ip address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get signed by ip address",
                "operationId": "signed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SessionType"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authentication.LDAPEndpointType": {
            "type": "object",
            "properties": {
                "domain_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "single_domain": {
                    "type": "boolean"
                },
                "tls_enable": {
                    "type": "boolean"
                }
            }
        },
        "authentication.RadiusEndpointType": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "gin.H": {
            "type": "object",
            "additionalProperties": {
                "type": "any"
            }
        },
        "types.AuthorizedResponseType": {
            "type": "object",
            "properties": {
                "issue": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "types.CaptivePortalConfigFundamentalType": {
            "type": "object",
            "properties": {
                "domain_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "html": {
                    "$ref": "#/definitions/types.HTMLType"
                },
                "mode": {
                    "type": "string"
                },
                "single_domain": {
                    "type": "boolean"
                }
            }
        },
        "types.CheckCredentialType": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "types.ConfigType": {
            "type": "object",
            "properties": {
                "administrator": {
                    "$ref": "#/definitions/types.CredentialType"
                },
                "allow_endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.EndpointType"
                    }
                },
                "bypass_networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ddos_prevention": {
                    "type": "boolean"
                },
                "domain_names": {
                    "type": "object",
                    "properties": {
                        "auth_domain_name": {
                            "type": "string"
                        },
                        "operator_domain_name": {
                            "type": "string"
                        }
                    }
                },
                "egress_interface": {
                    "type": "string"
                },
                "external_portal_url": {
                    "type": "string"
                },
                "fqdn_blocklist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "html": {
                    "$ref": "#/definitions/types.HTMLType"
                },
                "ldap": {
                    "$ref": "#/definitions/authentication.LDAPEndpointType"
                },
                "max_concurrent_session": {
                    "type": "integer"
                },
                "radius": {
                    "$ref": "#/definitions/authentication.RadiusEndpointType"
                },
                "redirect_url": {
                    "type": "string"
                },
                "secure_interface": {
                    "type": "string"
                },
                "session_idle": {
                    "type": "integer"
                }
            }
        },
        "types.CredentialType": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "types.EndpointType": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "types.ExtendConfigType": {
            "type": "object",
            "properties": {
                "administrator": {
                    "$ref": "#/definitions/types.CredentialType"
                },
                "allow_endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.EndpointType"
                    }
                },
                "bypass_networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ddos_prevention": {
                    "type": "boolean"
                },
                "domain_names": {
                    "type": "object",
                    "properties": {
                        "auth_domain_name": {
                            "type": "string"
                        },
                        "operator_domain_name": {
                            "type": "string"
                        }
                    }
                },
                "egress_interface": {
                    "type": "string"
                },
                "external_portal_url": {
                    "type": "string"
                },
                "fqdn_blocklist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "html": {
                    "$ref": "#/definitions/types.HTMLType"
                },
                "ldap": {
                    "$ref": "#/definitions/authentication.LDAPEndpointType"
                },
                "max_concurrent_session": {
                    "type": "integer"
                },
                "radius": {
                    "$ref": "#/definitions/authentication.RadiusEndpointType"
                },
                "redirect_url": {
                    "type": "string"
                },
                "secure_interface": {
                    "type": "string"
                },
                "session_idle": {
                    "type": "integer"
                },
                "status": {
                    "type": "object",
                    "properties": {
                        "egress_ip_address": {
                            "type": "string"
                        },
                        "secure_ip_address": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "types.HTMLType": {
            "type": "object",
            "properties": {
                "background_file_name": {
                    "type": "string"
                },
                "default_language": {
                    "type": "string"
                },
                "en_sub_title": {
                    "type": "string"
                },
                "en_title_name": {
                    "type": "string"
                },
                "logo_file_name": {
                    "type": "string"
                },
                "th_sub_title": {
                    "type": "string"
                },
                "th_title_name": {
                    "type": "string"
                }
            }
        },
        "types.InitializedType": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "types.SessionType": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "session_uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "api-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "COCO Captive Portal",
	Description:      "This is a COCO Captive Portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
