name: release
on:
  push:
    tags:
      - "v*-*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install package
        run: |
          sudo apt install -y build-essential libpcap0.8-dev make
      - name: Build UI
        working-directory: ./sign-in-ui
        run: |
          yarn install 
          yarn build
          tar -czf dist-ui.tar.gz build/*
          mv dist-ui.tar.gz ../dist-ui.tar.gz
      - name: Build CoCo Captive Portal
        run: |
          make build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            coco
            dist-ui.tar.gz
            LICENSE
