name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  Pre-Release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install package
        run: |
          sudo apt install -y build-essential libpcap0.8-dev make
      - name: Build Auth UI
        working-directory: ./sign-in-dev
        run: |
          yarn install 
          yarn build
          mv build dist-auth-ui
          tar -czf dist-auth-ui.tar.gz dist-auth-ui/*
          mv dist-auth-ui.tar.gz ../dist-auth-ui.tar.gz
      - name: Build Operator UI
        working-directory: ./operator-dev
        run: |
          yarn install 
          yarn build
          mv build dist-operator-ui
          tar -czf dist-operator-ui.tar.gz dist-operator-ui/*
          mv dist-operator-ui.tar.gz ../dist-operator-ui.tar.gz
      - name: Build CoCo Captive Portal
        run: |
          make build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            coco
            coco-installer
            config.yaml.sample
            coco-captive-portal.service
            dist-auth-ui.tar.gz
            dist-operator-ui.tar.gz
            LICENSE
